version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      #- pip install --upgrade awscli
  pre_build:
    commands:
      - echo Maven compilation started on `date`
      - mvn clean compile
      - echo Unit tests started on `date`
      - mvn test
      - echo Sonar analysis started on `date`
      - mvn sonar:sonar
  build:
    commands:
      - echo War packaging started on `date`
      - mvn war:exploded
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - mv target/ROOT .
artifacts:
  type: zip
  files: 
    - 'ROOT/**/*'
